spring.datasource.url=jdbc:mysql://localhost:3306/x2db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=HARINIdj#613

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# File upload settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# uploads dir relative to project working dir
app.upload.dir=uploads

server.port=8080

